# Creating a C environment

FROM debian

LABEL trahman="trahman@student.hive.fi"

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential vim git

# How to build it?
# docker build -t ex01 .

# How to run it?
# docker run --rm -ti ex01

# How to test it?
# go inside a container and make a simple c file, compile and run it