# Creating a C environment

FROM debian

MAINTAINER trahman.hive@gmail.com

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git

# How to build it?
# docker build -t ex01 .

# How to run it?
# docker run --rm -ti ex01