# This Dockerfile is according to the subjects
FROM ft-rails:on-build

EXPOSE 3000

CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]

# How to build it?
# After you build the ft-rails:on-build run this commands
# Go back to the root directory and run following command
# docker build -t ex02 .

# How to run it?
# docker run -it --rm -p 3000:3000 ex02

# How to test it?
# To test if the app is working, check your machines Char IP with the port
# 3000 in your web browser: 192.168.99.100:3000