FROM httpd:2.4

MAINTAINER trahman <trahman.hive@gmail.com>

COPY ./public-html/ /usr/local/apache2/htdocs/%

# How to build it?
# docker build -t ex03 .
#docker build -t my-apache2 .

# How to run it?
# docker run --rm -d -p 8080:80  ex03

#Link: https://hub.docker.com/_/httpd